Migration vers Webpack 5
Kozea/apparatus pull request #9
Opened 2021-01-05 16:27 UTC by notAro14

Pour faire la migration vers Webpack 5 côté projet, les modifs ressembleront à ça du coup.

Si vous voulez tester, et en attendant les modifs des commandes makefile, il faudra ajouter ces commandes dans le fichier **Makefile**

```makefile
serve-node-serve%: ## serve-node-server: Run node server
	$(LOG)
	WEBPACK_ENV=server NODE_ENV=development webpack 

serve-node-clien%: ## serve-node-client: Run node development files
	$(LOG)
	WEBPACK_ENV=browser NODE_ENV=development webpack serve

```

2021-01-06 11:34 UTC, gentooboontoo reviewed
LGTM :+1:

2021-01-07 09:54 UTC, gentooboontoo requested changes
J'ai une erreur suite à ce commit 761ee30.

2021-01-07 09:54 UTC, gentooboontoo commented on package.json
> -    "dart-sass": "^1.25.0",
Avec la suppression de `dart-sass`, j'ai désormais une erreur `MODULE_NOT_FOUND` quand je lance `make serve` ou `make build`:

```
[webpack-cli] Error: Cannot find module 'dart-sass'
Require stack:
- /home/julien/repositories/kozea/apparatus/node_modules/webpackozea/config.js
- /home/julien/repositories/kozea/apparatus/webpack.config.jsx
- /home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/lib/webpack-cli.js
- /home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/lib/bootstrap.js
- /home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/bin/cli.js
- /home/julien/repositories/kozea/apparatus/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (/home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/julien/repositories/kozea/apparatus/node_modules/webpackozea/config.js:10:14)
    at Module._compile (/home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/julien/repositories/kozea/apparatus/node_modules/webpackozea/config.js',
    '/home/julien/repositories/kozea/apparatus/webpack.config.jsx',
    '/home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/julien/repositories/kozea/apparatus/node_modules/webpack-cli/bin/cli.js',
    '/home/julien/repositories/kozea/apparatus/node_modules/webpack/bin/webpack.js'
  ]
}
```

2021-01-07 09:54 UTC, gentooboontoo commented on package.json
> +    "sass": "^1.32.0"
Cela ne devrait-il pas être une dépendance de dev ?

2021-01-07 10:11 UTC, notAro14 commented on package.json
> +    "sass": "^1.32.0"
Tu l'as testé avec quelle version de webpackozea ? Ca vient de là je pense. Sinon avec la version publiée aussi ça devrait être bon

2021-01-07 10:13 UTC, notAro14 commented on package.json
> +    "sass": "^1.32.0"
> Cela ne devrait-il pas être une dépendance de dev ?

Effectivement oui

2021-01-07 10:13 UTC, notAro14 commented on package.json
> -    "dart-sass": "^1.25.0",
Tu l'as testé avec quelle version de webpackozea ? Ca vient de là je pense. Sinon avec la version publiée aussi ça devrait être bon

2021-01-07 14:17 UTC, gentooboontoo commented on package.json
> -    "dart-sass": "^1.25.0",
Exact, j'ai encore oublié de le remettre comme je fais des clean / install à chaque fois.

Je pense que tu peux déjà mettre la version 1.0 RC dans les dépendances (`"webpackozea": ">=1.0.0-rc"`). Ça allégera la charge mentale :wink:.

2021-01-12 11:43 UTC, gentooboontoo approved these changes

2021-01-12 15:46 UTC, cmigazzi approved these changes
:+1:

2021-01-12 16:19 UTC, merged